// supabase/functions/camryn-intake/index.ts
//
// Inbound bridge: receives a "mark today complete" proposal FROM Front
// Door and writes it into camryn_pending_writes using the service-role
// key (bypasses RLS — server-to-server, authenticated by shared secret).
//
// REVISED PAYLOAD: earlier version accepted energy_level/symptom_notes/
// reflection — fields that don't correspond to any real Camryn write.
// This version accepts tasks_complete/tasks_total/checked_items, matching
// what handleSaveDay actually records.
//
// V1 SIMPLIFICATION (solo-user deployment): target user_id comes from a
// fixed environment variable (CAMRYN_TARGET_USER_ID). Must change before
// a second user is onboarded — see the deferred note at the bottom.

import { createClient } from 'npm:@supabase/supabase-js@2';

const INTAKE_SECRET = Deno.env.get('CAMRYN_INTAKE_SECRET');
const TARGET_USER_ID = Deno.env.get('CAMRYN_TARGET_USER_ID');
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

Deno.serve(async (req) => {
  if (req.method !== 'POST') {
    return json({ error: 'method not allowed' }, 405);
  }

  const providedSecret = req.headers.get('x-camryn-intake-secret');
  if (!INTAKE_SECRET || providedSecret !== INTAKE_SECRET) {
    return json({ error: 'unauthorized' }, 401);
  }

  if (!TARGET_USER_ID) {
    return json({ error: 'CAMRYN_TARGET_USER_ID not configured' }, 500);
  }

  let body: {
    action?: 'create' | 'verify';
    payload?: {
      tasks_complete?: number;
      tasks_total?: number;
      checked_items?: boolean[];
      target_date?: string;
    };
    id?: string;
  };

  try {
    body = await req.json();
  } catch {
    return json({ error: 'invalid JSON body' }, 400);
  }

  if (body.action === 'verify') {
    if (!body.id) return json({ error: 'missing id' }, 400);

    const { data, error } = await supabase
      .from('camryn_pending_writes')
      .select()
      .eq('id', body.id)
      .eq('user_id', TARGET_USER_ID)
      .single();

    if (error) return json({ error: error.message }, 404);
    return json({ data });
  }

  if (body.action === 'create') {
    // V1 is deliberately blunt: "mark today complete" is a single fixed
    // action (all 3 of today's tasks), not a per-task picker — Front Door
    // doesn't have visibility into what today's 3 tasks actually are
    // (that's generated by Camryn's dailyTasks(), based on phase/energy/
    // stress, which stays Camryn's own domain logic).
    const { data, error } = await supabase
      .from('camryn_pending_writes')
      .insert({
        user_id: TARGET_USER_ID,
        tasks_complete: 3,
        tasks_total: 3,
        checked_items: [true, true, true],
        target_date: body.payload?.target_date ?? new Date().toISOString().slice(0, 10),
      })
      .select()
      .single();

    if (error) return json({ error: error.message }, 500);
    return json({ data }, 201);
  }

  return json({ error: 'action must be "create" or "verify"' }, 400);
});

// ---------------------------------------------------------------------
// DEFERRED: multi-user identity mapping (unchanged from earlier version)
// ---------------------------------------------------------------------
// This function writes to a single, hardcoded CAMRYN_TARGET_USER_ID.
// Safe only because there is exactly one real user today. Before a
// second user exists: authenticate the incoming request as a specific
// Front Door user (not just a shared secret), and look up the target
// user_id via a real mapping table instead of hardcoding it.
